In [5]:
# activate the project environment
using Pkg; Pkg.activate(joinpath(@__DIR__, ".."));

  Activating project at `~/projects/julia-projects/dbscan`


In [6]:
using NearestNeighbors
using dbscan
using StaticArrays
using Dates
using CairoMakie
using LoggingExtras

In [7]:
fmt_logger = FormatLogger(stdout) do io, args
    # Write the module, level and message only
    println(io, args._module, " | ", "[", args.level, "] ", args.message)
end
debuglogger = MinLevelLogger(fmt_logger, Logging.Debug)

MinLevelLogger{FormatLogger, LogLevel}(FormatLogger(var"#15#16"(), VSCodeServer.IJuliaCore.IJuliaStdio{Base.PipeEndpoint, typeof(VSCodeServer.io_send_callback)}(IOContext(Base.PipeEndpoint(RawFD(16) open, 0 bytes waiting)), VSCodeServer.io_send_callback), true), Debug)

In [8]:
with_logger(debuglogger) do
    @debug "test"
end

Main | [Debug] test


In [9]:
# points = [SVector{3}(rand(3)) for i in 1:1_000_000]
# points = map(i -> rand(3), 1:1_000_000)
# points = [rand(3) for _ in 1:1_000_000]
points = rand(SVector{2, Float64}, 1_000_000)

1000000-element Vector{SVector{2, Float64}}:
 [0.6077669570992329, 0.732542843685898]
 [0.5112663800857348, 0.9248530760916017]
 [0.19264572871786279, 0.042971325814131656]
 [0.22059397817014503, 0.9579496404110045]
 [0.7265168359963103, 0.033173504050312386]
 [0.9046103621829878, 0.9009224075233079]
 [0.06168457051287679, 0.35853876328810386]
 [0.1443194365810503, 0.7068815098935161]
 [0.0016324042330693178, 0.6781623623607461]
 [0.7789188598014426, 0.009572433135428549]
 ⋮
 [0.9681991861369066, 0.37527097242790575]
 [0.29619857613602973, 0.1482616482339718]
 [0.05424593789882126, 0.6293545923464494]
 [0.813423983227912, 0.9125255654229673]
 [0.37467383729016956, 0.8380753126848403]
 [0.9045043656131125, 0.08186845103555351]
 [0.8467286368053654, 0.8927284808723013]
 [0.32667273834194355, 0.10357774036505174]
 [0.5039775389775468, 0.34075368006340645]

In [13]:
cluster_radius = 0.0005
min_pts = 3

3

In [14]:
with_logger(debuglogger) do 
    clusters = dbscan.DBSCAN(points, cluster_radius, min_pts; n_threads = 1)
end

dbscan | [Debug] 272 milliseconds to build kdtree
dbscan | [Debug] performing range searches
dbscan | [Debug] starting thread 1
dbscan | [Debug] 785 milliseconds to process thread 1
dbscan | [Debug] 1 millisecond to merge clusters 1
dbscan | [Debug] updating labels to cluster roots
dbscan | [Debug] 2 milliseconds to update labels
dbscan | [Debug] DBSCAN completed


ValueIterator for a Dict{Int64, Vector{Int64}} with 21331 entries. Values:
  [344150, 384883, 554652, 995085]
  [260227, 368282, 472226, 487119, 701636]
  [260353, 476766, 536209, 912434]
  [92032, 257967, 790985, 868976, 970347]
  [70465, 193788, 333370, 625545]
  [45343, 181972, 227978, 804659]
  [461699, 521784, 641744, 685599]
  [414860, 441304, 863549, 942406]
  [9875, 546080, 723026, 859261, 997124]
  [25486, 167712, 321739, 486929]
  [144536, 432949, 675154, 977596]
  [315096, 355117, 760437, 764237, 899287, 987141]
  [225459, 286640, 332651, 535742, 562954, 668959, 680669, 700406]
  [541474, 629587, 826171, 828325]
  [343972, 496716, 633338, 751008]
  [297827, 528623, 756498, 954453]
  [412944, 513540, 606786, 760112, 837645]
  [308609, 340317, 687001, 725940]
  [121254, 431518, 782889, 871624]
  ⋮

In [15]:
clusters = with_logger(debuglogger) do 
    dbscan.DBSCAN(points, cluster_radius, min_pts; n_threads = 4)
end

dbscan | [Debug] 311 milliseconds to build kdtree
dbscan | [Debug] performing range searches
dbscan | [Debug] starting thread 4
dbscan | [Debug] starting thread 1
dbscan | [Debug] starting thread 2
dbscan | [Debug] starting thread 3
dbscan | [Debug] 211 milliseconds to process thread 1
dbscan | [Debug] 218 milliseconds to process thread 4
dbscan | [Debug] 230 milliseconds to process thread 3
dbscan | [Debug] 232 milliseconds to process thread 2
dbscan | [Debug] 30 milliseconds to merge clusters 1
dbscan | [Debug] 11 milliseconds to merge clusters 2
dbscan | [Debug] 15 milliseconds to merge clusters 3
dbscan | [Debug] 17 milliseconds to merge clusters 4
dbscan | [Debug] updating labels to cluster roots
dbscan | [Debug] 2 milliseconds to update labels
dbscan | [Debug] DBSCAN completed


ValueIterator for a Dict{Int64, Vector{Int64}} with 21305 entries. Values:
  [152873, 221797, 776718, 984029]
  [92032, 257967, 790985, 868976, 970347]
  [70465, 193788, 333370, 625545]
  [45343, 181972, 227978, 804659]
  [461699, 521784, 641744, 685599]
  [414860, 441304, 863549, 942406]
  [9875, 546080, 723026, 859261, 997124]
  [225459, 286640, 332651, 535742, 562954, 668959, 680669, 700406]
  [541474, 629587, 826171, 828325]
  [169380, 285280, 434731, 931306]
  [297827, 528623, 756498, 954453]
  [308609, 340317, 687001, 725940]
  [121254, 431518, 782889, 871624]
  [248591, 374664, 479231, 699903, 976589]
  [1100, 106420, 221001, 402998, 942137]
  [50493, 533678, 613152, 628586, 725317, 880719]
  [189843, 374551, 628408, 673671, 880581]
  [658859, 695661, 712503, 887619]
  [243851, 266179, 751195, 996381]
  ⋮

In [16]:
# for i in eachindex(clusters)
#     if clusters[i] != 0 
#         println(i, ' ', clusters[i])
#         j = dbscan.find_root(i, clusters)
#         clusters[i] = j
#     end
# end

In [17]:
# for i in eachindex(clusters)
#     if clusters[i] != 0 
#         println(i, ' ', clusters[i])
#     end
# end

In [18]:
minimum(map(length, clusters))

4

In [19]:
tree = KDTree(points)

KDTree{SVector{2, Float64}, Euclidean, Float64, SVector{2, Float64}}
  Number of points: 1000000
  Dimensions: 2
  Metric: Euclidean(0.0)
  Reordered: true

In [20]:
# inrange(tree, points[263613], cluster_radius)

In [21]:
function draw_circle!(ax, x0, y0, r)
    t = 0:0.01:2pi
    x = x0 .+ r .* cos.(t)
    y = y0 .+ r .* sin.(t)
    lines!(ax, x, y; color = :black, alpha = 0.1)
end

draw_circle! (generic function with 1 method)

In [22]:
# f = Figure()
# ax = Axis(f[1, 1])

# scatter!(points; color = :gray, markersize = 2.0)
# for (id, cluster) in enumerate(clusters)
#     scatter!(points[cluster])
#     for (x0, y0) in points[cluster]
#         draw_circle!(ax, x0, y0, cluster_radius)
#     end
# end

# f

In [23]:
# wrap timings in a function to avoid global variables causing problems
function run_tests(N; n_threads = 1)
    # times = zeros(N)
    times = []
    for i in 1:N
        points = rand(SVector{3, Float64}, 1_000_000)
        t0 = now()
        labels = dbscan.DBSCAN(points, 0.0005, 3, n_threads = n_threads)
        tf = now()
        push!(times, canonicalize(tf - t0))
    end
    return times
end

run_tests (generic function with 1 method)

In [24]:
times_1 = run_tests(10; n_threads = 1)

10-element Vector{Any}:
 1 second, 306 milliseconds
 1 second, 157 milliseconds
 1 second, 498 milliseconds
 1 second, 220 milliseconds
 1 second, 356 milliseconds
 1 second, 144 milliseconds
 1 second, 157 milliseconds
 1 second, 288 milliseconds
 1 second, 160 milliseconds
 1 second, 228 milliseconds

In [25]:
times_2 = run_tests(10; n_threads = 2)

10-element Vector{Any}:
 1 second, 29 milliseconds
 940 milliseconds
 994 milliseconds
 1 second, 28 milliseconds
 874 milliseconds
 1 second, 10 milliseconds
 902 milliseconds
 976 milliseconds
 887 milliseconds
 1 second, 27 milliseconds

In [26]:
times_4 = run_tests(10; n_threads = 4)

10-element Vector{Any}:
 777 milliseconds
 944 milliseconds
 793 milliseconds
 950 milliseconds
 791 milliseconds
 763 milliseconds
 880 milliseconds
 832 milliseconds
 886 milliseconds
 718 milliseconds

In [ ]:
# smaller dataset for plotting