In [1]:
# activate the project environment
using Pkg; Pkg.activate(joinpath(@__DIR__, ".."));

  Activating project at `~/projects/julia-projects/dbscan`


In [2]:
using NearestNeighbors
using dbscan
using StaticArrays
using Dates

In [3]:
# points = [SVector{3}(rand(3)) for i in 1:1_000_000]
# points = map(i -> rand(3), 1:1_000_000)
# points = [rand(3) for _ in 1:1_000_000]
points = rand(SVector{3, Float64}, 1_000_000)

1000000-element Vector{SVector{3, Float64}}:
 [0.41818580984114806, 0.511225159800065, 0.1053746526452558]
 [0.21496318123785407, 0.9270647006237394, 0.030875945794987092]
 [0.8791605841404367, 0.3003996877354672, 0.9678938117469734]
 [0.9931664010398962, 0.5158879726569758, 0.8321192410621853]
 [0.03997747351765224, 0.192953529018151, 0.14327209190041323]
 [0.6569607409101775, 0.746324774065101, 0.3749117436218494]
 [0.8533871851476981, 0.7174209686900972, 0.9588561715361719]
 [0.404234908950207, 0.593249986003003, 0.435270556298323]
 [0.81044259673191, 0.89630195199058, 0.6375473064830703]
 [0.6933324596970801, 0.8772629835257686, 0.3931583277850974]
 ⋮
 [0.5904273505600103, 0.57959898419157, 0.5497836285943685]
 [0.6341411088571606, 0.21669092313996619, 0.9218466893362992]
 [0.06836494888908318, 0.1272938028699705, 0.7070336569633565]
 [0.4477200827261063, 0.03852009268364798, 0.1858964547860491]
 [0.1370917199362729, 0.48995428829242094, 0.1097349557143592]
 [0.6413784637648435, 0.

In [4]:
chunk2 = dbscan.DBSCAN(points, 0.01, 3; n_chunks = 4)

1000000-element Vector{Int64}:
 931040
 998179
 990070
 796125
 885884
 768707
 925755
 762914
 858920
 975523
      ⋮
 999992
 999993
 999994
 999995
 999996
 999997
 999998
 999999
      0

In [5]:
# wrap timings in a function to avoid global variables causing problems
function run_tests(N; n_chunks = 1)
    times = zeros(N)
    for i in 1:N
        points = rand(SVector{3, Float64}, 1_000_000)
        t0 = now()
        labels = dbscan.DBSCAN(points, 0.01, 3, n_chunks = n_chunks)
        tf = now()
        times[i] = (tf - t0).value / 1000
    end
    return times
end

run_tests (generic function with 1 method)

In [9]:
times_1 = run_tests(10; n_chunks = 1)

10-element Vector{Float64}:
 1.282
 1.325
 1.322
 1.33
 1.314
 1.36
 1.269
 1.261
 1.304
 1.452

In [10]:
times_2 = run_tests(10; n_chunks = 2)

10-element Vector{Float64}:
 0.91
 0.939
 0.828
 0.802
 0.854
 0.854
 0.847
 0.852
 0.888
 0.839

In [11]:
times_4 = run_tests(10; n_chunks = 4)

10-element Vector{Float64}:
 0.671
 0.664
 0.667
 0.645
 0.621
 0.704
 0.672
 0.626
 0.624
 0.644

In [14]:
# smaller dataset for plotting

10-element Vector{Float64}:
 6.27
 6.43
 6.32
 6.04
 5.92
 6.1899999999999995
 5.845000000000001
 5.699999999999999
 5.869999999999999
 6.455