In [1]:
# activate the project environment
using Pkg; Pkg.activate(joinpath(@__DIR__, ".."));

  Activating project at `~/projects/julia-projects/dbscan`


In [2]:
using NearestNeighbors
using dbscan
using StaticArrays
using Dates
using CairoMakie
using LoggingExtras

In [3]:
fmt_logger = FormatLogger(stdout) do io, args
    # Write the module, level and message only
    println(io, args._module, " | ", "[", args.level, "] ", args.message)
end
debuglogger = MinLevelLogger(fmt_logger, Logging.Debug)

MinLevelLogger{FormatLogger, LogLevel}(FormatLogger(var"#11#12"(), VSCodeServer.IJuliaCore.IJuliaStdio{Base.PipeEndpoint, typeof(VSCodeServer.io_send_callback)}(IOContext(Base.PipeEndpoint(RawFD(16) open, 0 bytes waiting)), VSCodeServer.io_send_callback), true), Debug)

In [4]:
with_logger(debuglogger) do
    @debug "test"
end

Main | [Debug] test


In [5]:
# points = [SVector{3}(rand(3)) for i in 1:1_000_000]
# points = map(i -> rand(3), 1:1_000_000)
# points = [rand(3) for _ in 1:1_000_000]
points = rand(SVector{2, Float64}, 1_000_000)

1000000-element Vector{SVector{2, Float64}}:
 [0.41944535293789764, 0.7748462892841721]
 [0.11015513556679479, 0.5992713825334546]
 [0.6528374395421539, 0.6733820035155462]
 [0.29083240570550073, 0.7971193690874131]
 [0.9503840884812856, 0.2704416416392377]
 [0.9805558203421374, 0.7691900047302844]
 [0.4081539475795909, 0.5010693722419971]
 [0.7475565645738004, 0.8836602373486051]
 [0.3522738917042597, 0.43560637450910167]
 [0.5413059186492146, 0.807140124270942]
 ⋮
 [0.668381689117044, 0.4929243385754788]
 [0.680522046088059, 0.18272539329793802]
 [0.939308795395123, 0.8278274031944424]
 [0.7366314277084444, 0.9114243657481882]
 [0.09910615801049927, 0.753048408162902]
 [0.7911650468763552, 0.5873259628100225]
 [0.005716493337293738, 0.3271723545874228]
 [0.0078020872374516825, 0.409308289668336]
 [0.841006897819883, 0.5783098048552827]

In [6]:
cluster_radius = 0.0005
min_pts = 3

3

In [7]:
with_logger(debuglogger) do 
    clusters = dbscan.DBSCAN(points, cluster_radius, min_pts; n_threads = 1)
end

dbscan | [Debug] 284 milliseconds to build kdtree
dbscan | [Debug] performing range searches
dbscan | [Debug] starting thread 1
dbscan | [Debug] 564 milliseconds to process thread 1
dbscan | [Debug] 70 milliseconds to merge clusters 1
dbscan | [Debug] updating labels to cluster roots
dbscan | [Debug] 20 milliseconds to update labels
dbscan | [Debug] DBSCAN completed


ValueIterator for a Dict{Int64, Vector{Int64}} with 21597 entries. Values:
  [80466, 631442, 669205, 894512]
  [132410, 153795, 404213, 477400, 569539]
  [305994, 534774, 614257, 666911]
  [29498, 363245, 535745, 969756]
  [42593, 90375, 188182, 545776, 863443, 977344]
  [21328, 481253, 647479, 720432, 829441]
  [31332, 261438, 307222, 552449]
  [77867, 234406, 346167, 627526, 686051, 716720]
  [128362, 131911, 239729, 422830, 561542, 633870]
  [268038, 698128, 808986, 851596]
  [433556, 443528, 558980, 763621]
  [294743, 320741, 724343, 912499]
  [114796, 120722, 520671, 664870]
  [97123, 215750, 234536, 284559]
  [191119, 360452, 747196, 864253]
  [403039, 566985, 838769, 948534]
  [513573, 663231, 850879, 988760]
  [151514, 647456, 706527, 941272]
  [32332, 128007, 538817, 948987]
  ⋮

In [8]:
clusters = with_logger(debuglogger) do 
    dbscan.DBSCAN(points, cluster_radius, min_pts; n_threads = 4)
end

dbscan | [Debug] 296 milliseconds to build kdtree
dbscan | [Debug] performing range searches
dbscan | [Debug] starting thread 2
dbscan | [Debug] starting thread 1
dbscan | [Debug] starting thread 4
dbscan | [Debug] starting thread 3
dbscan | [Debug] 136 milliseconds to process thread 2
dbscan | [Debug] 146 milliseconds to process thread 3
dbscan | [Debug] 154 milliseconds to process thread 4
dbscan | [Debug] 162 milliseconds to process thread 1
dbscan | [Debug] 77 milliseconds to merge clusters 1
dbscan | [Debug] 16 milliseconds to merge clusters 2
dbscan | [Debug] 14 milliseconds to merge clusters 3
dbscan | [Debug] 15 milliseconds to merge clusters 4
dbscan | [Debug] updating labels to cluster roots
dbscan | [Debug] 2 milliseconds to update labels
dbscan | [Debug] DBSCAN completed


ValueIterator for a Dict{Int64, Vector{Int64}} with 21597 entries. Values:
  [132410, 153795, 404213, 477400, 569539]
  [305994, 534774, 614257, 666911]
  [29498, 363245, 535745, 969756]
  [301083, 492150, 887802, 953809]
  [77867, 234406, 346167, 627526, 686051, 716720]
  [433556, 443528, 558980, 763621]
  [128362, 131911, 239729, 422830, 561542, 633870]
  [647383, 684158, 872362, 933654]
  [59501, 492728, 500237, 863129]
  [86344, 122784, 368760, 485153, 839510, 989519]
  [89060, 100656, 286743, 993723]
  [294743, 320741, 724343, 912499]
  [397003, 567019, 700406, 843019]
  [114796, 120722, 520671, 664870]
  [403039, 566985, 838769, 948534]
  [415485, 435736, 902829, 919396]
  [14410, 662553, 894378, 940139]
  [68820, 243762, 692781, 841418]
  [513573, 663231, 850879, 988760]
  ⋮

In [9]:
# for i in eachindex(clusters)
#     if clusters[i] != 0 
#         println(i, ' ', clusters[i])
#         j = dbscan.find_root(i, clusters)
#         clusters[i] = j
#     end
# end

In [10]:
# for i in eachindex(clusters)
#     if clusters[i] != 0 
#         println(i, ' ', clusters[i])
#     end
# end

In [11]:
minimum(map(length, clusters))

4

In [12]:
tree = KDTree(points)

KDTree{SVector{2, Float64}, Euclidean, Float64, SVector{2, Float64}}
  Number of points: 1000000
  Dimensions: 2
  Metric: Euclidean(0.0)
  Reordered: true

In [13]:
# inrange(tree, points[263613], cluster_radius)

In [14]:
function draw_circle!(ax, x0, y0, r)
    t = 0:0.01:2pi
    x = x0 .+ r .* cos.(t)
    y = y0 .+ r .* sin.(t)
    lines!(ax, x, y; color = :black, alpha = 0.1)
end

draw_circle! (generic function with 1 method)

In [15]:
# f = Figure()
# ax = Axis(f[1, 1])

# scatter!(points; color = :gray, markersize = 2.0)
# for (id, cluster) in enumerate(clusters)
#     scatter!(points[cluster])
#     for (x0, y0) in points[cluster]
#         draw_circle!(ax, x0, y0, cluster_radius)
#     end
# end

# f

In [16]:
# wrap timings in a function to avoid global variables causing problems
function run_tests(N; n_threads = 1)
    # times = zeros(N)
    times = []
    for i in 1:N
        points = rand(SVector{3, Float64}, 1_000_000)
        t0 = now()
        labels = dbscan.DBSCAN(points, 0.0005, 3, n_threads = n_threads)
        tf = now()
        push!(times, canonicalize(tf - t0))
    end
    return times
end

run_tests (generic function with 1 method)

In [17]:
times_1 = run_tests(10; n_threads = 1)

10-element Vector{Any}:
 1 second, 146 milliseconds
 1 second, 76 milliseconds
 976 milliseconds
 1 second, 63 milliseconds
 955 milliseconds
 1 second, 146 milliseconds
 915 milliseconds
 1 second, 90 milliseconds
 1 second, 198 milliseconds
 1 second, 32 milliseconds

In [18]:
times_2 = run_tests(10; n_threads = 2)

10-element Vector{Any}:
 884 milliseconds
 767 milliseconds
 714 milliseconds
 750 milliseconds
 755 milliseconds
 905 milliseconds
 756 milliseconds
 815 milliseconds
 861 milliseconds
 782 milliseconds

In [19]:
times_4 = run_tests(10; n_threads = 4)

10-element Vector{Any}:
 632 milliseconds
 732 milliseconds
 644 milliseconds
 683 milliseconds
 811 milliseconds
 656 milliseconds
 736 milliseconds
 663 milliseconds
 635 milliseconds
 651 milliseconds

In [20]:
# smaller dataset for plotting